package com.se2020.course.registration.enums;

public enum PermissionsEnum {
    // ALL USER 
    ALL_GET_COURSE, ALL_LOG_IN, 

    // ADMIN
    ADMIN_CHANGE_PASSWORD,
    ADMIN_ADD_USER, ADMIN_DELETE_USER, ADMIN_MODIFY_USER, ADMIN_GET_USER,
    ADMIN_ADD_COURSE, ADMIN_DELETE_COURSE, ADMIN_MODIFY_COURSE,  

    // STUDENT
    STUDENT_CHANGE_PASSWORD, STUDENT_MODIFY_PROFILE, 
    STUDENT_REGISTER_COURSE, STUDENT_CANCEL_COURSE, STUDENT_GET_MY_COURSE,
}
