package com.se2020.course.registration.enums;

public enum PermissionsEnum {
    // ALL USER 
    ALL_GET_COURSE, ALL_LOG_IN, 
    CHANGE_PASSWORD,
    // ADMIN
    ADMIN_ADD_USER, ADMIN_DELETE_USER, ADMIN_MODIFY_USER_ACCOUNT, ADMIN_GET_USER, ADMIN_EDIT_STUDENT_INFO,
    ADMIN_ADD_COURSE, ADMIN_DELETE_COURSE, ADMIN_MODIFY_COURSE,  

    // STUDENT
    STUDENT_EIDT_PROFILE, 
    STUDENT_REGISTER_COURSE, STUDENT_CANCEL_COURSE, STUDENT_GET_MY_COURSE,
}
